export const ADD_FOOD_REQUEST = 'ADD_FOOD_REQUEST';
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
export const ADD_FOOD_FAIL = 'ADD_FOOD_FAIL';
export const SEARCH_FOOD_REQUEST = 'SEARCH_FOOD_REQUEST';
export const SEARCH_FOOD_SUCCESS = 'SEARCH_FOOD_SUCCESS';
export const SEARCH_FOOD_FAIL = 'SEARCH_FOOD_FAIL';
